**Please follow PEP8 during writing code in Python. Readability matters**

# NumPy

1. Write a NumPy program to test if two arrays are element-wise equal within a tolerance.

In [76]:
import numpy as np

A = np.array([[2, 4, 2.00], [2, 6, 7]])
B = np.array([[2, 4, 2], [2, 6.0, 7]])
np.allclose(A, B)

True

2. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [26]:
m = 3
n = 4
v = 10

M = np.array([[x for x in range(v + y*4, v + y*4 + n)] for y in range(m)])
M

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

*3. Write a NumPy program to create an 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [27]:
n = 4
v = 10

M = np.array([[(x+y) % 2 for x in range(n)] for y in range(n)])
M

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

4. Write a NumPy program to compute the cross product of two given vectors.

In [77]:
a = np.array([3, 5, 1, ])
b = np.array([4, 1, -2])

np.cross(a, b)

array([-11,  10, -17])

5. Write a NumPy program to calculate the QR decomposition of a given matrix.

In [29]:
M = np.array([[x for x in range(v + y*4, v + y*4 + n)] for y in range(m)])

np.linalg.qr(M)

(array([[-0.40160966,  0.81978229,  0.40824829],
        [-0.56225353,  0.13116517, -0.81649658],
        [-0.7228974 , -0.55745196,  0.40824829]]),
 array([[-2.48997992e+01, -2.65865598e+01, -2.82733204e+01,
         -2.99600810e+01],
        [ 0.00000000e+00,  3.93495501e-01,  7.86991003e-01,
          1.18048650e+00],
        [ 0.00000000e+00,  0.00000000e+00,  4.70391795e-16,
          1.02857729e-15]]))

6. Write a NumPy program to find the most frequent value in an array.

In [47]:
M = np.array([[3, 34, 3, 2, 6], [2, 3, 5, 5, 5]])  # 2 dim, 2 most frequent val
M = np.reshape(M, M.size)

count = np.bincount(M)
res = np.argwhere(count == np.amax(count))
print(res.flatten().tolist())

[3, 5]


7. Write a NumPy program to create a random vector of size 10 and sort it

In [78]:
size = 10
v = np.random.random(size)
print('Vector:',v)

v = np.sort(v)
print('Sorted:',v)

Vector: [0.18940386 0.02174471 0.04639567 0.50324214 0.10954373 0.14883101
 0.12902569 0.00614494 0.89964281 0.60541086]
Sorted: [0.00614494 0.02174471 0.04639567 0.10954373 0.12902569 0.14883101
 0.18940386 0.50324214 0.60541086 0.89964281]


*8. Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degrees.

In [81]:
def trig_func(data):
    for d in data:
        d = np.deg2rad(d)
        yield np.array([round(np.sin(d), 3),
                        round(np.cos(d), 3), round(np.tan(d), 3)])


angles = [2, -24, 180, 0, 32492]
res = trig_func(angles)

for r in res:
    print(r)

[0.035 0.999 0.035]
[-0.407  0.914 -0.445]
[ 0. -1. -0.]
[0. 1. 0.]
[  0.999  -0.035 -28.636]


**9. Write a NumPy program to calculate distance matrix D (MxN) between each row of the matrix X (MxD) and each row of the matrix Y (NxD) using the L2 norm. Implement your algorithm using `for` loops. Try to implement the logic without any loops using only vectorized operations.

In [84]:
def dist_l2(x, y):
    res = 0
    for i in range(len(x)):
        res += (x[i]-y[i])** 2
    return res ** (1 / 2)


def dist_with_loops(X, Y):
    dist = np.array([])
    for rx in X:
        for ry in Y:
            dist = np.r_[dist, dist_l2(rx, ry)]
    return np.reshape(dist, (len(X), len(Y)))


def dist_without_loops(X, Y):
    return np.array([[np.linalg.norm(rx - ry) for ry in Y] for rx in X])


X = np.array([[1, 3, 4], [23, 5, 3], [3, 0, 9]])
Y = np.array([[8, 5, 6], [4, 2, 4]])

print('Function with loops:', dist_with_loops(X, Y))
print('Function without loops:', dist_without_loops(X, Y))

Function with loops: [[ 7.54983444  3.16227766]
 [15.29705854 19.26136028]
 [ 7.68114575  5.47722558]]
Function without loops: [[ 7.54983444  3.16227766]
 [15.29705854 19.26136028]
 [ 7.68114575  5.47722558]]
